# This file was autogenerated in base/version_git.sh
immutable GitVersionInfo
    commit::String
    commit_short::String
    branch::String
    build_number::Int
    date_string::String
    tagged_commit::Bool
    fork_master_distance::Int
    fork_master_timestamp::Float64
end

const GIT_VERSION_INFO = GitVersionInfo(
    "806cd0e0dbb476fd3aaf6bf48bfeafb3c339b4ac",
    "806cd0e*",
    "rand32",
    1270,
    "2014-01-27 19:46 UTC",
    false,
    2,
    1390817176.
)
